### ISSUE TITLE
"Configure Models" Window Stuck on Loading in v0.4.5

### ISSUE THREAD

**Issue by Yirenxs** [open-webui/open-webui#7386] opened 2024-11-26 14:53 UTC
Hi,

I'm experiencing an issue with the latest v0.4.5 version of Open Web-UI. When I navigate to Admin Settings > Models > Configure, the "Configure Models" window pops up but gets stuck on the loading spinner and doesn't load properly.

Here are the steps I tried to resolve this:

Restarted the Open Web-UI Docker container in Portainer.
Checked for any visible errors, but the problem persists.
The issue happens consistently and prevents me from accessing the model configuration.

Environment Details:

Version: v0.4.5
Deployment: Docker (managed via Portainer)
Please let me know if additional logs or information are required.

Thank you!

**Comment by clduab11** [comment] 2024-11-26 14:55
Same with me!

![image](https://github.com/user-attachments/assets/d5e15b73-a828-4637-99fc-7f0aee2defa6)

Restarted by OWUI Docker, made sure Watchtower or nothing else was wrong.
No visible errors anywhere else.
Tried from multiple different devices and encountered the same issue.

**Comment by fl0w1nd** [comment] 2024-11-26 14:59
I am also on version 0.4.5, but I haven't encountered this issue

**Comment by dezerving** [comment] 2024-11-26 16:36
Duplicate of #7375.

**Closed** 2024-11-26 16:45 UTC
