### ISSUE TITLE
Docker conteiner does not start correctly Windows 10

### ISSUE THREAD

**Issue by devdimit93** [open-webui/open-webui#884] opened 2024-02-24 02:52 UTC
Can not install Open-webui on Windows 10 with Ollama 0.1.27 via Docker. Container is always restarted with error
```
2024-02-24 05:32:07 Traceback (most recent call last):
2024-02-24 05:32:07   File "/usr/local/bin/uvicorn", line 8, in <module>
2024-02-24 05:32:07     sys.exit(main())
2024-02-24 05:32:07              ^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
2024-02-24 05:32:07     return self.main(*args, **kwargs)
2024-02-24 05:32:07            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
2024-02-24 05:32:07     rv = self.invoke(ctx)
2024-02-24 05:32:07          ^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
2024-02-24 05:32:07     return ctx.invoke(self.callback, **ctx.params)
2024-02-24 05:32:07            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
2024-02-24 05:32:07     return __callback(*args, **kwargs)
2024-02-24 05:32:07            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 418, in main
2024-02-24 05:32:07     run(
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
2024-02-24 05:32:07     server.run()
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 62, in run
2024-02-24 05:32:07     return asyncio.run(self.serve(sockets=sockets))
2024-02-24 05:32:07            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
2024-02-24 05:32:07     return runner.run(main)
2024-02-24 05:32:07            ^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
2024-02-24 05:32:07     return self._loop.run_until_complete(task)
2024-02-24 05:32:07            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 69, in serve
2024-02-24 05:32:07     config.load()
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 458, in load
2024-02-24 05:32:07     self.loaded_app = import_from_string(self.app)
2024-02-24 05:32:07                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 21, in import_from_string
2024-02-24 05:32:07     module = importlib.import_module(module_str)
2024-02-24 05:32:07              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
2024-02-24 05:32:07     return _bootstrap._gcd_import(name[level:], package, level)
2024-02-24 05:32:07            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
2024-02-24 05:32:07   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
2024-02-24 05:32:07   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
2024-02-24 05:32:07   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
2024-02-24 05:32:07   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
2024-02-24 05:32:07   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-02-24 05:32:07   File "/app/backend/main.py", line 19, in <module>
2024-02-24 05:32:07     from apps.rag.main import app as rag_app
2024-02-24 05:32:07   File "/app/backend/apps/rag/main.py", line 83, in <module>
2024-02-24 05:32:07     embedding_functions.SentenceTransformerEmbeddingFunction(
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/chromadb/utils/embedding_functions.py", line 72, in __init__
2024-02-24 05:32:07     self.models[model_name] = SentenceTransformer(model_name, device=device)
2024-02-24 05:32:07                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 190, in __init__
2024-02-24 05:32:07     modules = self._load_sbert_model(
2024-02-24 05:32:07               ^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/site-packages/sentence_transformers/SentenceTransformer.py", line 1093, in _load_sbert_model
2024-02-24 05:32:07     self._model_config = json.load(fIn)
2024-02-24 05:32:07                          ^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
2024-02-24 05:32:07     return loads(fp.read(),
2024-02-24 05:32:07            ^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
2024-02-24 05:32:07     return _default_decoder.decode(s)
2024-02-24 05:32:07            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
2024-02-24 05:32:07     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-02-24 05:32:07                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-24 05:32:07   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
2024-02-24 05:32:07     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-02-24 05:32:07 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
I used next command 
`docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main`

Tested with 3333, 8883 and other ports - does not work. Also disabled firewall.
Remote server in local network with any ports also does not work. Tested by next command 
`docker run -d -p 3000:8080 -e OLLAMA_API_BASE_URL=https://192.168.0.1 -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main`
Also tried install ghcr.io/open-webui/open-webui:git-f69c0d2 . Got same error

Ollama correctly work with console on the  127.0.0.1:11434

**Comment by justinh-rahb** [comment] 2024-02-24 03:02
your `docker run` commands are lacking the `:11434/api` part of the API URL, try:

```bash
docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway:11434/api -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
```

**Comment by devdimit93** [comment] 2024-02-24 03:17
I started it with old version :git-b793b5a 
Full command in console
`docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:git-b793b5a`
It work for me with localhost and in local network with any ports

**Comment by devdimit93** [comment] 2024-02-24 03:28
> First read the [Ollama FAQ section](https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-windows) about environment variables. You must set `OLLAMA_HOST=0.0.0.0:11434` and `OLLAMA_ORIGINS=*`
> 
> Your `docker run` commands are lacking the `:11434/api` part of the API URL, try:
> 
> ```shell
> docker run -d -p 3000:8080 -e OLLAMA_API_BASE_URL=https://192.168.0.1:11434/api -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
> ```
> 
> Also, on most networks `192.168.0.1` would be your router, so that likely wouldn't be correct if that's what you actually used.

In final experiments with network connection I just connected 2 laptops with ehternet wire and configured static IP address manualy.
Modification of the system variables did not help for last release - same JSON error in docker logs

**Comment by justinh-rahb** [comment] 2024-02-24 03:31
`:git-b793b5a` is 5 days old, if there's a broken build it's more likely to have been more recent. Try walking back from the top here: [tagged images](https://github.com/open-webui/open-webui/pkgs/container/open-webui/versions?filters%5Bversion_type%5D=tagged)

**Comment by devdimit93** [comment] 2024-02-24 04:14
The last correct version for my laptops is git-792fe98
Next git-c391692 is already return JSON error

**Comment by justinh-rahb** [comment] 2024-02-24 04:19
For anyone else looking, that was from PR #772: https://github.com/open-webui/open-webui/commit/c3916927bb566f1514eaf3e705d4be8129dc382b

**Comment by jannikstdl** [comment] 2024-02-24 12:28
I will have a look, thanks

**Comment by jannikstdl** [comment] 2024-02-24 12:40
@devdimit93 I cant reproduce this error on Win 11:
![image](https://github.com/open-webui/open-webui/assets/69747628/ea9d1fad-4004-46e5-89f0-0af4cdbaf5c5)

Can you give more information on your hardware?

Also can you try to build the Dockerfile with ENV `RAG_EMBEDDING_MODEL` set to `"intfloat/multilingual-e5-base"`  and run it again?

**Comment by devdimit93** [comment] 2024-02-24 17:57
> @devdimit93 I cant reproduce this error on Win 11: ![image](https://private-user-images.githubusercontent.com/69747628/307520891-ea9d1fad-4004-46e5-89f0-0af4cdbaf5c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3OTc1ODksIm5iZiI6MTcwODc5NzI4OSwicGF0aCI6Ii82OTc0NzYyOC8zMDc1MjA4OTEtZWE5ZDFmYWQtNDAwNC00NmU1LTg5ZjAtMGFmNGNkYmFmNWM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI0VDE3NTQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjYmY5YTQ2NzQxNWQzYjBhZTlkZTAxYWE3NjE2MzExZGMzMjMwYWFkOTllN2NmN2ZiNDVmMjkyZGFmZWQxY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fuyh3PKgEInYY9JgAP8GR1yBDeNCQiYgNNA5zN8z0ZY)
> 
> Can you give more information on your hardware?
> 
> Also can you try to build the Dockerfile with ENV `RAG_EMBEDDING_MODEL` set to `"intfloat/multilingual-e5-base"` and run it again?

Thank you! It is work correctly now.
I added `-e RAG_EMBEDDING_MODEL=intfloat/multilingual-e5-base ` and problem has been fixed.
Full command
`docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data -e RAG_EMBEDDING_MODEL=intfloat/multilingual-e5-base --name open-webui --restart always ghcr.io/open-webui/open-webui:main `

**Comment by tjbck** [comment] 2024-02-24 20:40
It should've worked without the env var, @jannikstdl could you look into this? Thanks!

**Comment by jannikstdl** [comment] 2024-02-24 20:46
Yes, should. 

But this is the first issue with the standard embedding model. 
Others aren't facing this behavior. 
Maybe I can recreate this error. 
Will have a look.

**Comment by jannikstdl** [comment] 2024-02-24 21:50
@devdimit93 can you try to clone the project and build the **default** Dockerfile with `docker build -t open-webui-test .` and run it. Do you get the same issue?

**Comment by devdimit93** [comment] 2024-02-25 03:22
> @devdimit93 can you try to clone the project and build the **default** Dockerfile with `docker build -t open-webui-test .` and run it. Do you get the same issue?
Container correctly start and work after maualy building. I used next commands:
```
C:\Users\Dmitrii> git clone https://github.com/open-webui/open-webui
C:\Users\Dmitrii> cd .\open-webui\
C:\Users\Dmitrii\open-webui> docker build -t open-webui-test .
C:\Users\Dmitrii\open-webui> docker run -p 3000:8080 open-webui-test
```

**Comment by jannikstdl** [comment] 2024-02-25 08:36
@devdimit93 ok thanks! 


@tjbck think we can close this since this seems to be an error with an old version of the image. 

If there a more issues coming op in the future we see if this is a common problem but i don't think it is and for now it works.  I also can't reproduce it.

**Comment by tjbck** [comment] 2024-02-25 18:47
Thanks guys!

**Closed by tjbck** 2024-02-25 18:47 UTC
