### ISSUE TITLE
bug: firefox "add files" modal issue

### ISSUE THREAD

**Issue by ralyodio** [open-webui/open-webui#867] opened 2024-02-23 12:03 UTC
have to refresh page to get rid of it.

**Comment by jannikstdl** [comment] 2024-02-23 12:06
I dont have this issue with the latest version in firefox. Can you give more information?

**Comment by jannikstdl** [comment] 2024-02-23 12:28
i dont think that this is an issue with the UI. I can try this with Linux later.

**Comment by ralyodio** [comment] 2024-02-23 12:31
i see. well closing the dialog is still an issue. maybe my screen is too small and its hidden. should at least be closable with [ESC] button

**Comment by btzs** [comment] 2024-03-06 05:59
I am on Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0

The modal appears when trying to copy any content (CTRL+C)

![image](https://github.com/open-webui/open-webui/assets/55090626/fdfa043c-1494-4758-ab69-f0a6db9bf1f9)

**Comment by btzs** [comment] 2024-03-13 13:42
Interestingly I cannot reproduce the problem on my system anymore. Still the same browser version

**Comment by insunaa** [comment] 2024-03-13 22:19
I still have the same issue. I uploaded a file ***once*** using the file selector and ever since then this `Add Files` modal randomly appears and doesn't go away unless I refresh the page (despite me not trying to upload any files)

**Comment by NiLon** [comment] 2024-03-16 11:35
This issue still exists in Firefox 123.0.1. It's somewhat on and off issue. Most reproducible way I have managed to trigger this is by dealing with files in any of the chats. Then opening a new chat (doesn't need to have any file). After that you make the browser inactive, like focus another window in another monitor and that makes the overlay to appear. After that it appears each time the browser loses focus.

**Comment by ralyodio** [comment] 2024-03-16 11:38
we just need to add a close button or close on ESC

**Comment by NiLon** [comment] 2024-03-16 11:53
> we just need to add a close button or close on ESC

That would be nice to have, but it's kind of workaround and doesn't fix the actual issue. It's bit triggering to have a close the modal each time you want to prompt with a workflow that makes use of multiple windows. Once the problem triggers once, it won't stop happening. 🫠

**Comment by jannikstdl** [comment] 2024-03-16 12:45
> This issue still exists in Firefox 123.0.1. It's somewhat on and off issue. Most reproducible way I have managed to trigger this is by dealing with files in any of the chats. Then opening a new chat (doesn't need to have any file). After that you make the browser inactive, like focus another window in another monitor and that makes the overlay to appear. After that it appears each time the browser loses focus.

Can't reproduce this behavior on Linux Debian with Firefox 115.8.0esr

What deployment type are you using?

**Comment by NiLon** [comment] 2024-03-16 12:55
> What deployment type are you using?
I see this on docker deployment. I tested that flatpak version of Firefox has this problem as well. Have not tested the ESR, but it's rather irrelevant tbh.

**Comment by gibru** [comment] 2024-04-14 15:34
Still happens but thanks for adding the option to close it with ESC.

We have two up-to-date Arch Linux setups with KDE Plasma and it only happens on one machine. I tried to reproduce this behavior and while it almost never happens on one machine, with the second PC it's rather peculiar: it only happens when (a lot of?) text is inside the clipboard (e.g. with copying a text from a word document to paste into open webui's textbox). For example, openwebui is open in Firefox:

- switching to the word document (change window focus from Firefox to word processor) without copying text from the word document and switching back to Firefox and open webui, the add files modal does not appear.
- switching to the word document (change window focus from Firefox to word processor) and copying text from the word document (with the content now inside the clipboard) and switching back to Firefox and open webui, the add files modal does appear.
- as long as the content is inside the clipboard, switching between Firefox and other windows will make the add files modal appear when switching back to open webui.
- clearing the clipboard solves the issue and as long as nothing new is added, it won't appear.

Don't know if that helps narrowing down the issue, but I thought I'd share.

**Comment by ralyodio** [comment] 2024-04-14 15:44
it almost seems like a browser bug

**Comment by c3fr4** [comment] 2024-04-30 22:34
Hey everyone, I am experiencing the same issue and I think I've found some more information on this. When you encounter the bug, try to clear your clipboard using the KDE Plasma tray icon. As you will notice, once you clear the clipboard, the modal bug does not appear. I doubt this is an open-webui related problem, because I am experiencing similar issues in the github web editor. Whenever I have something in my clipboard, the cursor won't show up in the editor. It's really annoying. I also have issues in WhatsApp Web, when dragging a file inside a chat. You guys will probably have similar problems. Not sure what the cause of this is, but it's definetly a strange bug.

**Comment by c3fr4** [comment] 2024-04-30 22:35
@gibru I just read your post. Can you try and see if both machines are using wayland?

**Comment by c3fr4** [comment] 2024-04-30 22:38
I've just tested using X11 instead of wayland and that does the trick. This seems to be a bug in wayland.

**Comment by Cephra** [comment] 2024-04-30 23:05
Hey everyone, I am experiencing the same issue and I think I've found some more information on this. When you encounter the bug, try to clear your clipboard using the KDE Plasma tray icon. As you will notice, once you clear the clipboard, the modal bug does not appear. I doubt this is an open-webui related problem, because I am experiencing similar issues in the github web editor. Whenever I have something in my clipboard, the cursor won't show up in the editor. It's really annoying. I also have issues in WhatsApp Web, when dragging a file inside a chat. You guys will 

**Update:** probably have similar problems. Not sure what the cause of this is, but it's definetly a strange bug.
I've just tested using X11 instead of wayland and that does the trick. This seems to be a bug in wayland.

**Comment by gibru** [comment] 2024-05-01 04:21
@Cephra 

Yes, I use Wayland on both of my machines. Nice find! I've still got some other quirks with it so in a way I'm not suprised ;)

**Comment by justinh-rahb** [comment] 2024-05-01 16:51
Wayland strikes again! Unless something new comes to light, I am going to close this issue as there's probably not much we can do about it.

**Closed by justinh-rahb** 2024-05-01 16:51 UTC

**Comment by coxde** [comment] 2024-05-02 10:33
A very hacky workaround for uBlock users: add a custom filter rule `#dropzone`, so the thing won't bother you.
