### ISSUE TITLE
feat: multiple OpenAI connections

### ISSUE THREAD

**Issue by NinjaPerson24119** [open-webui/open-webui#693] opened 2024-02-10 01:24 UTC
**Is your feature request related to a problem? Please describe.**

I really like your UI. And I want to like Ollama, but it refuses to keep my models loaded, so I've started using Llama.cpp server directly because I can't be losing 2 minutes every time i need a query.

I'd like to be able to continue using this UI, but I need to be able to call Llama.cpp server instead.

**Describe the solution you'd like**

Allow me to enter the Llama.cpp server IP and select it as a model.

**Describe alternatives you've considered**

I mean, I could just use a different UI, but I like this one.

**Additional context**

 Nothing to add.

**Comment by tjbck** [comment] 2024-02-10 01:42
Hi, just tested with `llama-cpp-python[server]` by modifying the OpenAI API Base URL value from Settings > External, seems to be working as intended. Let me know if you're encountering issues!

![image](https://github.com/ollama-webui/ollama-webui/assets/25473318/4032ff97-dad2-429d-b7fa-0ee6fae2b758)

**Comment by NinjaPerson24119** [comment] 2024-02-10 01:44
I figured I could do that, but I want to be able to use OpenAI as well.

My workflow is something like:
- Use GPT-4 for complex, short queries, but limit this because it's expensive
- Use Llama.cpp for a large model I want to keep loaded
- Use Ollama for smaller models I want to load on-demand

**Comment by tjbck** [comment] 2024-02-10 02:12
I'll take a look and see how this could be natively implemented from the webui, but in the meantime, LiteLLM would be useful here. Related: #604

**Comment by NinjaPerson24119** [comment] 2024-02-10 03:43
Interesting. Using an adapter pattern seems like the winning move for development effort / maintenance. Since it's a standardization layer, I probably can't actually use it at this point unless the UI gives me an option to select options within that provider.

At a basic level, I think it'd be sufficient to allow adding APIs that are OpenAI compatible. Adding a simple + to make a list on the screen would do it.

This is what I'm able to do in Continue, https://continue.dev/docs/model-setup/configuration. And if want to run something that's not compatible I can write a proxy in Python pretty quickly.

**Comment by justinh-rahb** [comment] 2024-02-10 03:46
Hi @NinjaPerson24119, these are all great suggestions that we've been discussing recently in #604, glad to hear there's others with similar ideas.

**Comment by NinjaPerson24119** [comment] 2024-02-10 19:27
Got this working locally https://github.com/ollama-webui/ollama-webui/pull/697 @tjbck @justinh-rahb

**Comment by jukofyork** [comment] 2024-04-10 02:44
Sorry to bump an old thread, but can I ask did you find anything missing when using the llama.cpp Server's OpenAI API compatible endpoint vs Ollama?

I've sadly had my fill of Ollama bugs but do like using OpenWebUI.

How does it handle things like prompt templates, etc as I assume the OpenAI API  wouldn't need these customizing? Is it all done on the server side and OpenWebUI uses whatever it sees?

**Comment by tjbck** [comment] 2024-04-10 03:52
@jukofyork I'm hoping to clear out quite a bit of backlogs starting from later this week, and I will get back to this as well so stay tuned! 

I'll close this feature request, let's continue our discussion for direct llama.cpp integration here: #1483

**Closed by tjbck** 2024-04-10 03:52 UTC
Labels: enhancement, good first issue, help wanted, core
