### ISSUE TITLE
admin panel displays the administrator's name instead of the user's name.

### ISSUE THREAD

**Issue by lijiajun1997** [open-webui/open-webui#2302] opened 2024-05-16 07:18 UTC
# Bug Report

## Description

**Bug Summary:**
When the "Display the username instead of 'You' in the Chat" setting is enabled by an administrator, viewing other users' chat records in the admin panel displays the administrator's name instead of the user's name.

**Steps to Reproduce:**
1. Log in as an administrator.
2. Enable the "Display the username instead of 'You' in the Chat" setting.
3. Navigate to the admin panel.
4. View the chat records of another user.

**Expected Behavior:**
The chat records should display the actual user's name.

**Actual Behavior:**
The chat records display the administrator's name instead of the user's name.

## Environment

- **Open WebUI Version:**0.1.124
- **Ollama (if applicable):**N/A

- **Operating System:Ubuntu **20.04
- **Browser (if applicable):**Chrome 

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [X] I have included the browser console logs.
- [X] I have included the Docker container logs.

## Logs and Screenshots
N/A
**Browser Console Logs:**
N/A

**Docker Container Logs:**
N/A

**Screenshots (if applicable):**
![image](https://github.com/open-webui/open-webui/assets/156336589/7074024e-b4e5-4609-bedd-48ac1dfdfc41)
![image](https://github.com/open-webui/open-webui/assets/156336589/1c6d99bb-07f4-4593-8e69-de823046f26c)
![image](https://github.com/open-webui/open-webui/assets/156336589/312e9bdb-7644-44cb-b656-8e1bac7f5df6)

## Installation Method

docker

## Additional Information

N/A

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by Silentoplayz** [comment] 2024-05-16 20:43
The reported behavior is not a bug, but rather a misunderstanding of the` Display the username instead of 'You' in the Chat` setting. This option only applies to personal chats, not shared chats or admin panel views. When viewing another user's chat records in the admin panel, it's expected that the administrator's name is displayed, not the user's name. The setting does not affect the admin panel or shared chats. Although the current behavior is intended, it may not be all too desirable. Perhaps this is an opportunity to revisit and refine the feature to better meet user expectations, but for now, it's working as designed.

**Comment by tjbck** [comment] 2024-05-18 21:39
Fixed on dev.

**Closed by tjbck** 2024-05-18 21:39 UTC
