### ISSUE TITLE
WEBUI_AUTH=Fales stops launching of OpenUI

### ISSUE THREAD

**Issue by wcwong22000** [open-webui/open-webui#5566] opened 2024-09-21 04:28 UTC
# Bug Report
Setting WEBUI_AUTH=Fales will stop launching of OpenUI
Setting WEBUI_AUTH=True will allow launching of OpenUI OK
## Installation Method
Docker Compose
[Describe the method you used to install the project, e.g., git clone, Docker, pip, etc.]
Docker
## Environment
Ubuntu 24.04.1
- **Open WebUI Version:** [e.g., v0.3.11]
0.3.23
- **Ollama (if applicable):** [e.g., v0.2.0, v0.1.32-rc1]
0.3.11
- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
Ubuntu 24.04.1
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]
Edge 
**Confirmation:**

- [Y ] I have read and followed all the instructions provided in the README.md.
- [Y] I am on the latest version of both Open WebUI and Ollama.
- [ N] I have included the browser console logs.
- [ N] I have included the Docker container logs.
- [ ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:
 It should launch directly without any login. There was no issue with 0.3.21. 
[Describe what you expected to happen.]

## Actual Behavior:
It stopped at launch screen (and did not show the screen prompting for login and password either) and loops forever.
[Describe what actually happened.]

## Description

**Bug Summary:**
[Provide a brief but clear summary of the bug]

## Reproduction Details

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots/Screen Recordings (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Additional Information

Docker compose file content:

version: '3.8'

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    network_mode: host
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
      - PORT=3088
      - WEBUI_AUTH=False

volumes:
  open-webui:

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by thams** [comment] 2024-09-21 13:21
You have a typo. Use "False" not "Fales"

However: see this issue. There is a bug when running the container on a Linux host.

https://github.com/open-webui/open-webui/issues/5575

**Comment by thams** [comment] 2024-09-21 13:24
Noting that #5575 has been closed as a duplicate of this.... 

I'l drop this here:

When `WEBUI_AUTH=False`

the error occurs on Linux hosts but not Mac hosts.

**Closed** 2024-09-21 13:34 UTC
